sequenceDiagram
participant S as Spell
participant T as Texture manager
loop Ask after some time
    S->>T: Hey, set my muscle definition.
    T->>S: I'll give you this alpha. Remember it.
    Note over S: Remembers assigned number.
    Note over S: Number says alpha is calculated.<br>Wait a little before next enquiry.
    Note over S: Number says alpha is constant.<br>Wait medium time before <br>next enquiry.
    Note over S: Number says is invalid race.<br>Wait a lot before next enquiry.
end
