graph TD

start((PC/NPC))
getRace[Get race]
knownRace{Known race?}
getSex[Get sex]
rippedMode[Get ripped mode<br>from Lua]
calcAlpha[Calculate alpha]
setLyr[Set Override Layers]
rValid[Return <valid>]
rinvalid[Return <invalid>]
stop((End))


start --> getRace --> knownRace
knownRace -->|no| rinvalid
knownRace -->|yes| rippedMode --> getSex --> calcAlpha -->setLyr --> rValid --> stop
rinvalid --> stop
