sequenceDiagram
participant M as MCM
participant P as Player
participant T as Texture manager
M->>T: Hey, make Player ripped
T-->>P: Adds ripped spell
loop Ripped spell
    P->>T: Hey, set my muscle definition
    P->>P: Wait before asking again
end
M->>T: Hey, make Player not ripped
T-->>P: Clear ()
Note left of T: Removes ripped spell
